/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.newairlines;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinee
 */
public class passengerInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form passengerInfo
     */
    public passengerInfo() {
        initComponents();
        LoadData();
    }
    connect con = new connect();
    connect con1 = new connect();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Passenger Id", "Name", "Phone Number", "Flight Id", "Seat", "Amount Due"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
        public void LoadData()
    {
        try {
//             con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","");
//             pst = con.prepareStatement("SELECT * from ticket");
//                          pst = con.prepareStatement("SELECT * from ticket");
            String str = "select * from ticket";
            ResultSet rs = con.s.executeQuery(str);
//             ResultSet rs = pst.executeQuery();
             
//             ResultSetMetaData rsm = rs.getMetaData();
//             int c;
//             c = rsm.getColumnCount();
             
             DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
             Df.setRowCount(0);
             
             while(rs.next())
             {  
                String custid = rs.getString("cid");
                String str1 = "select * from customer where id = '"+custid+"'";
                ResultSet rs1 = con1.s.executeQuery(str1);
                while(rs1.next()) {
                    Vector v2 = new Vector();

                    for(int i = 1; i<= 6; i ++)
                    {
                        v2.add(rs1.getString("id"));
                        v2.add(rs1.getString("fname")+rs1.getString("lname"));
                        v2.add(rs1.getString("phone"));
                        v2.add(rs.getString("fid"));
                        v2.add(rs.getString("seat num"));
                        v2.add(rs.getString("price"));

    //                    v2.add(rs.getString("date"));

                    }

                     Df.addRow(v2);
                }
              
                 
                 
             }
             
             
             
             
             
             
        } catch (SQLException ex) {
            Logger.getLogger(bookTickets.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }
    



}
